TaskFlow/TaskFlow.WebApp/Controllers/AuthController.cs
using AutoMapper;
using MediatR;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Razor.TagHelpers;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.Identity.Client;
using System.ComponentModel.Design.Serialization;
using TaskFlow.Application.Autentication.Handlers;
using TaskFlow.Application.Contracts.Authentication;
using TaskFlow.Domain.Entities.Users;
using TaskFlow.WebApp.API.Interfaces;

namespace TaskFlow.WebApi.Controllers
{
    public class AuthController : Controller
    {
        private readonly IAuth _authService;
        private readonly CookieGenerator _cookieGenerator;
        public AuthController(IAuth authService, CookieGenerator cookieGenerator)
        {
            _authService = authService ?? throw new ArgumentNullException(nameof(authService), "IAuth service is null");
            _cookieGenerator = cookieGenerator ?? throw new ArgumentNullException(nameof(cookieGenerator), "CookieGenerator is null");
        }

        // GET: AuthController
        [HttpGet]
        public ActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Register(RegisterRequestApi request,CancellationToken token)
        {
            if(!ModelState.IsValid)
            {
                return View(request);
            }

            var response = await _authService.Register(request, token);

            if (response == null)
            {
                ModelState.AddModelError("", "Registration failed. Please try again.");
                return View(request);
            }

            return RedirectToAction("Login");

        }




        [HttpGet]
        public ActionResult Login()
        {
            return View();
        }


        [HttpPost]
        public async Task<IActionResult> Login(LoginRequest request, CancellationToken token)
        {
            if (!ModelState.IsValid)
            {
                return View(request);
            }

            var response = await _authService.Login(request, token);

            if (response == null)
            {
                ModelState.AddModelError("", "Login failed. Please try again.");
                return View(request);
            }

            _cookieGenerator.CreateCookie(response);

            return RedirectToAction("Profile", "Home");
        }


        // GET: AuthController/Details/5
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> Register(RegisterRequest request, CancellationToken token)
        //{
        //    if (!ModelState.IsValid)
        //    {
        //        return View(request);
        //    }

        //    var member = _mapper.Map<Member>(request);
        //    var result = await _userManager.CreateAsync(member, request.Password);
        //    if (!result.Succeeded)
        //    {
        //        foreach(var error in result.Errors)
        //        {
        //            ModelState.TryAddModelError(error.Code, error.Description);
        //        }

        //        return View(request);
        //    }
        //    return View(request);
        //}

        // GET: AuthController/Create
        //public ActionResult Create()
        //{
        //    return View();
        //}

        //// POST: AuthController/Create
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Create(IFormCollection collection)
        //{
        //    try
        //    {
        //        return RedirectToAction(nameof(Index));
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}

        //// GET: AuthController/Edit/5
        //public ActionResult Edit(int id)
        //{
        //    return View();
        //}

        //// POST: AuthController/Edit/5
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Edit(int id, IFormCollection collection)
        //{
        //    try
        //    {
        //        return RedirectToAction(nameof(Index));
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}

        //// GET: AuthController/Delete/5
        //public ActionResult Delete(int id)
        //{
        //    return View();
        //}

        //// POST: AuthController/Delete/5
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Delete(int id, IFormCollection collection)
        //{
        //    try
        //    {
        //        return RedirectToAction(nameof(Index));
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}
    }
}

TaskFlow/TaskFlow.WebApp/Controllers/WorkflowController.cs
using MediatR;
using Microsoft.AspNetCore.Mvc;
using NuGet.Common;
using TaskFlow.Application.WorkFlow.Projects.Queries;
using TaskFlow.WebApp.API.Interfaces;
using TaskFlow1.Models;

namespace TaskFlow.WebApp.Controllers
{
    public class WorkflowController : Controller
    {
        private readonly IProject _projectApiService;


        public WorkflowController(IProject projectApiService)
        {
            _projectApiService = projectApiService ?? throw new NullReferenceException("IProject API Service is null");
        }

        [HttpGet]
        public async Task<IActionResult> ProjectBoardView(ushort Id, CancellationToken token) 
        {

            var result = await _projectApiService.GetProjectById(Id, token);
            if(result == null)
            {
                return View("Error", new ErrorViewModel { RequestId = $"Project with id {Id} not found" });
            }
            return View(result); 
        }

        [HttpGet]
        public async Task<IActionResult> ProjectListView(CancellationToken token)
        {
            try
            {
                var result = await _projectApiService.GetAllProjectsAsync(token);
                if (result == null || !result.Any()) return NotFound(result);
                return View(result);
            }
            catch
            {
                return BadRequest("Failed to retrieve project list");
            }
        }

        [HttpGet]
        public async Task<IActionResult> ViewPage(CancellationToken token) 
        {
            try
            {
                var result = await _projectApiService.GetAllProjectsAsync(token);
                if (result == null || !result.Any()) return NotFound(result);
                return View(result);
            }
            catch
            {
                return BadRequest("Failed to retrieve project list");
            }
        }
    }
}

TaskFlow/TaskFlow.WebApp/Views/Shared/View.cshtml
@model TaskFlow1.Program

@{
    ViewData["Title"] = "View";
}

<h1>View</h1>

<h4>Program</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="View">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TaskFlow/TaskFlow.WebApp/Views/Shared/_Aside.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<style>

     #projectDropdown {
          display: block !important;
          visibility: visible !important;
     }
     

</style>

<script>

      document.addEventListener("DOMContentLoaded", () => {
         FetchProjectsAsync();
     });

     function showProjectModal() {
       const modal = new bootstrap.Modal(document.getElementById('newProjectModal'));
       modal.show();
     }

     function toggleProjectDropdown(event) {
          event.stopPropagation();
          const dropdown = event.currentTarget.closest('li').querySelector('.project-dropdown');
          dropdown.classList.toggle('show');
     }

     document.addEventListener('click', function () {
          document.querySelectorAll('.project-dropdown').forEach(d => d.classList.remove('show'));
     });

      function toggleProjectMenu() {
         const menu = document.getElementById('projectDropdownMenu');
         menu.classList.toggle('show');
     }

     // Optional: close on click outside
     document.addEventListener('click', function (e) {
         const menu = document.getElementById('projectDropdownMenu');
         const toggle = document.querySelector('.dropdown-toggle-project');

         if (!toggle.contains(e.target)) {
             menu.classList.remove('show');
         }
     });


     function RenderProjectsAsync(projects) {
         const projectDropdown = document.getElementById("projectDropdown");

         // Clear all existing items
         projectDropdown.innerHTML = ``;
         // Append each project as a <li>
         projects.forEach(project => {
            const li = document.createElement("li");

            let projName = project.name;
            projName = projName.length > 6 ? projName.substring(0, 6) + '...' : projName; //truncate the project name if too long
            console.log(projName);

          li.className = "px-2 py-1"; // padding for spacing

          li.innerHTML = `
               <div class="d-flex justify-content-between align-items-center w-100">
               <a href="/Workflow/ProjectBoardView/${project.id}"
                    class="nav-link text-dark d-flex align-items-center gap-2 p-0"
                    id="proj_name" title="${project.name}" style="flex-grow:1;">
                    <i class="material-symbols-rounded opacity-5">folder</i>
                    <span class="nav-link-text">${projName}</span>
               </a>

               <div class="btn-group">
                    <button type="button" class="btn p-0 bg-transparent border-0 dropdown-toggle"
                         data-bs-toggle="dropdown" aria-expanded="false">
                    </button>
                    <ul class="dropdown-menu dropdown-menu-end">
                    <li>
                    <a class="dropdown-item delete-project-btn" data-project-id="${project.id}">
                         Delete Project
                    </a>
                    </li>
                    </ul>
               </div>
               </div>
          `;

             projectDropdown.appendChild(li);
         });
     }

      async function FetchProjectsAsync() {
         const response = await fetch('https://localhost:7006/api/Workflow/GetAllProjects');
         if (response.ok) {
             const projects = await response.json();
             RenderProjectsAsync(projects);
         } else {
             console.error("Failed to fetch projects");
         }
         console.log(response);
     }

          // Handle project deletion
     document.addEventListener("click", function(event) {
         const deleteBtn = event.target.closest(".delete-project-btn");
         if (deleteBtn) {
             const projectId = deleteBtn.getAttribute("data-project-id");
             if (projectId) {
                 DeleteProjectAsync(projectId);
             }
         }
     });

      async function DeleteProjectsAsync(projectId) {
         const confirmed = confirm("Are you sure you want to delete this project?");
         if (!confirmed) return;

         const response = await fetch(`https://localhost:7006/api/Workflow/DeleteProject?Id=${projectId}`, {
             method: 'DELETE'
         });

          if (response.ok) {
         RenderProjectsAsync(await fetchProjects()); // Refresh projects after delete
          } else {
              alert("Failed to delete project.");
          }
     }

</script>

<aside class="sidenav navbar navbar-vertical navbar-expand-xs border-radius-lg fixed-start ms-2  bg-white my-2" id="sidenav-main">
     <div class="sidenav-header">
          <i class="fas fa-times p-3 cursor-pointer text-dark opacity-5 position-absolute end-0 top-0 d-none d-xl-none" aria-hidden="true" id="iconSidenav"></i>
          <a class="navbar-brand px-4 py-3 m-0" href=" https://demos.creative-tim.com/material-dashboard/pages/dashboard " target="_blank">
               <img src="~/assets/img/logo-ct-dark.png" class="navbar-brand-img" width="26" height="26" alt="main_logo">
               <span class="ms-1 text-sm text-dark">Taskflow</span>
          </a>
     </div>
     <hr class="horizontal dark mt-0 mb-2">
     <div class="collapse navbar-collapse  w-auto " id="sidenav-collapse-main">
          <ul class="navbar-nav">
               <li class="nav-item project-item position-relative">
                    <div class="nav-link d-flex justify-content-between align-items-center @(ViewData["ActivePage"] as string == "Template" ? "active bg-gradient-dark text-white" : "text-dark")">
                         <div class="d-flex align-items-center">

                              <a class="@(ViewData["ActivePage"] as string == "Template" ? "active bg-gradient-dark text-white" : "text-dark")" href="@Url.Action("Template", "Home")">
                                   <i class="material-symbols-rounded opacity-5">table_view</i>
                                   <span class="nav-link-text ms-1">Projects</span>
                              </a>

                              <!-- Dropdown Toggle (small inline) -->
                              <div class="dropdown-toggle-project position-relative ms-2">
                                   <span class="dropdown-toggle-icon" onclick="toggleProjectMenu(event)">▾</span>

                                   <div class="project-dropdown-menu" id="projectDropdownMenu">
                                        <button type="button" class="nav-link text-dark ps-4 bg-transparent border-0" onclick="showProjectModal()">
                                             <i class="material-symbols-rounded opacity-5">add_circle</i>
                                             <span class="nav-link-text ms-2">New Project</span>
                                        </button>

                                        <button type="button" class="nav-link text-dark ps-4 bg-transparent border-0">
                                             <a class="@(ViewData["ActivePage"] as string == "Template" ? "active bg-gradient-dark text-white" : "text-dark")" href="@Url.Action("ProjectBoardView", "Workflow")">ProjectBoardView</a>
                                        </button>

                                        <button type="button" class="nav-link text-dark ps-4 bg-transparent border-0">
                                             <a class="@(ViewData["ActivePage"] as string == "Template" ? "active bg-gradient-dark text-white" : "text-dark")" href="@Url.Action("ProjectListView", "Workflow")">ProjectListView</a>
                                        </button>

                                        <button type="button" class="nav-link text-dark ps-4 bg-transparent border-0">
                                             <a class="@(ViewData["ActivePage"] as string == "Template" ? "active bg-gradient-dark text-white" : "text-dark")" href="@Url.Action("ViewPage", "Workflow")">ViewPage</a>
                                        </button>
                                   </div>
                              </div>
                         </div>

                         <span class="project-actions text-white" >
                              <i class="material-symbols-rounded">add</i>
                         </span>
                    </div>


                    <ul class="project-dropdown list-unstyled ms-4 mt-1" id="projectDropdown">

                         <li>
                              <a href="@Url.Action("Create", "Project")" class="nav-link text-dark ps-4">
                                   <i class="material-symbols-rounded opacity-5">add_circle</i>
                                   <span class="nav-link-text ms-2">New Project</span>
                              </a>
                         </li>

                    </ul>
               </li>
               <li class="nav-item mt-3">
                    <h6 class="ps-4 ms-2 text-uppercase text-xs text-dark font-weight-bolder opacity-5">Account pages</h6>
               </li>

               <li class="nav-item">
                    <a class="nav-link @(ViewData["ActivePage"] as string == "Profile" ? "active bg-gradient-dark text-white" : "text-dark")" href="@Url.Action("Profile", "Home")">
                         <i class="material-symbols-rounded opacity-5">person</i>
                         <span class="nav-link-text ms-1">Profile</span>
                    </a>
               </li>

               <li class="nav-item">
                    <a class="nav-link text-dark" href="@Url.Action("Login", "Auth")">
                         <i class="material-symbols-rounded opacity-5">login</i>
                         <span class="nav-link-text ms-1">Sign In</span>
                    </a>
               </li>

               <li class="nav-item">
                    <a class="nav-link text-dark" href="@Url.Action("Register", "Auth")">
                         <i class="material-symbols-rounded opacity-5">assignment</i>
                         <span class="nav-link-text ms-1">Sign Up</span>
                    </a>
               </li>

          </ul>
     </div>
</aside>

TaskFlow/TaskFlow.WebApp/Views/Shared/_Empty_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
     <meta charset="utf-8" />
     <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
     <title>@ViewBag.Title</title>

     <!-- Favicon -->
     <link rel="apple-touch-icon" sizes="76x76" href="@Url.Content("~/assets/img/apple-icon.png")">
     <link rel="icon" type="image/png" href="@Url.Content("~/assets/img/favicon.png")">

     <link href="@Url.Content("/css/bundle.css")" rel="stylesheet" />
     <!-- Bootstrap -->
     <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" />

     <!-- Main CSS -->
     <link id="pagestyle" rel="stylesheet" href="@Url.Content("~/assets/css/material-dashboard.css?v=3.2.0")" />     
</head>

<body>
     @await RenderSectionAsync("Section", true)

     @RenderBody()
     <script src="@Url.Content("/js/core.js")"></script>
     <script>
          window.addEventListener('DOMContentLoaded', function () {
              const inputs = document.querySelectorAll('.input-group input');

              inputs.forEach(input => {
                  if (input.value.trim() !== '') {
                      input.parentElement.classList.add('is-filled');
                  }

                  input.addEventListener('input', function () {
                      if (this.value.trim() !== '') {
                          this.parentElement.classList.add('is-filled');
                      } else {
                          this.parentElement.classList.remove('is-filled');
                      }
                  });
              });

              // Optional: reinitialize if needed
              if (window.md?.input?.init) {
                  md.input.init();
              }
          });
     </script>
</body>
</html>

TaskFlow/TaskFlow.WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
     <meta charset="utf-8" />
     <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
     <title>@ViewBag.Title</title>

     <!-- Favicon -->
     <link rel="apple-touch-icon" sizes="76x76" href="@Url.Content("~/assets/img/apple-icon.png")">
     <link rel="icon" type="image/png" href="@Url.Content("~/assets/img/favicon.png")">

     <!-- Fonts and icons -->
     <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Inter:300,400,500,600,700,900" />
     <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Rounded:opsz,wght,FILL,GRAD@24,400,0,0" />

     <link href="@Url.Content("/css/bundle.css")" rel="stylesheet" />

     <!-- Main CSS -->
     <link id="pagestyle" rel="stylesheet" href="@Url.Content("~/assets/css/material-dashboard.css?v=3.2.0")" />
</head>

<body>
     @await Html.PartialAsync("_Navbar")
     @await Html.PartialAsync("_Aside", (IEnumerable<TaskFlow.Domain.Entities.Projects.Project>)ViewBag.Projects)
     <main class="main-content position-relative max-height-vh-100 h-100 border-radius-lg">

          @await RenderSectionAsync("Menu")

          @RenderBody()
     </main>

     @await Html.PartialAsync("_NewPartialProjectView")

     <script async defer src="https://buttons.github.io/buttons.js"></script>

     <script src="@Url.Content("/js/core.js")"></script>
    



     @* @await Html.PartialAsync("_NewPartialProjectView", true); *@
</body>

</html>

TaskFlow/TaskFlow.WebApp/Views/Shared/_Navbar.cshtml
<nav class="navbar navbar-main navbar-expand-lg px-0 mx-3 shadow-none border-radius-xl" id="navbarBlur" data-scroll="true">
     <div class="container-fluid py-1 px-3">
          <div class="collapse navbar-collapse mt-sm-0 mt-2 me-md-0 me-sm-4" id="navbar">
               <div class="ms-md-auto pe-md-3 d-flex align-items-center">
               </div>
               <ul class="navbar-nav d-flex align-items-center  justify-content-end">
                    <li class="nav-item dropdown pe-3 d-flex align-items-center">
                         <a href="javascript:;" class="nav-link text-body p-0" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-expanded="false">
                              <i class="material-symbols-rounded">notifications</i>
                         </a>
                    </li>
                    <li class="nav-item d-flex align-items-center">
                         <a href="@Url.Action("Profile", "Home")" class="nav-link text-body font-weight-bold px-0">
                              <i class="material-symbols-rounded">account_circle</i>
                         </a>
                    </li>
               </ul>
          </div>
     </div>
</nav>

TaskFlow/TaskFlow.WebApp/Views/Shared/_NewPartialProjectView.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}




<div class="modal fade" id="newProjectModal" tabindex="-1" aria-labelledby="newProjectModalLabel" aria-hidden="true">
     <div class="modal-dialog modal-dialog-centered">
          <div class="modal-content bg-dark text-white">
               <div class="modal-header border-0">
                    <h5 class="modal-title text-white" id="newProjectModalLabel">New Project</h5>
                    <button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal" aria-label="Close"></button>
               </div>
               <div class="modal-body">
                    <form method="post">
                         <fieldset>
                              <div class="row mb-3">
                                   <label for="ProjectName" class="col-sm-3 col-form-label text-white">Project Name:</label>
                                   <div class="col-sm-9">
                                        <input type="text" class="form-control bg-secondary text-white border-light" id="ProjectName" name="ProjectName" />
                                        @Html.ValidationMessage("ProjectName")
                                   </div>
                              </div>
                              <div class="row mb-3">
                                   <label for="ProjectDescription" class="col-sm-3 col-form-label text-white">Project Description:</label>
                                   <div class="col-sm-9">
                                        <input type="text" class="form-control bg-secondary text-white border-light" id="ProjectDescription" name="ProjectDescription" />
                                        @Html.ValidationMessage("ProjectDescription")
                                   </div>
                              </div>
                              <div class="text-end">
                                   <button type="submit" class="btn btn-primary">Submit</button>
                              </div>
                         </fieldset>
                    </form>
               </div>
          </div>
     </div>
</div>